### ISSUE TITLE
similar project

### ISSUE THREAD

**Issue by mshanemc** [senorshaun/homebridge-griddy#1]
I'm opening an issue to let you know of a similar project I created over here:
https://github.com/mshanemc/homebridge-griddy

**Comment by senorshaun** [comment]
Cool stuff. I thought about doing the price, and I was going to do it based on Intensity, until I saw prices spike over $3/kwh. I guess you can ceiling it at 100% but then I realized I don't really care about price, I only care if it is higher than I want (I dont turn on anything if the price goes lower than a certain price). Kind of just a think where you build a plugin for your own use case and then add stuff in if people ask. 

Looks like you cleaned up some of my late night coding and separated out the platform and accessory pieces as you have a couple switches.
Are you NPM published? We may look at merging so all the functionality is under on npm name. Just make different pieces available in the config based on user case

**Comment by mshanemc** [comment]
I started from the TS plugin template (prefer TS) which is structured as platform/accessories https://github.com/homebridge/homebridge-plugin-template

I was trying to solve the problem of, "what if it's 5c all morning but going to be $5 this afternoon...I'd want to use that 5c power" because if my threshold is 4c it'll never run and I'll be sweating all day.

npm (namespaced) https://www.npmjs.com/package/@mshanemc/homebridge-griddy

I chose light sensor to accommodate a high-end value https://developers.homebridge.io/#/characteristic/CurrentAmbientLightLevel

**Comment by senorshaun** [comment]
gritty is dead
